server {
    listen 443 ssl;
    server_name 192.168.12.53;

    ssl_certificate /etc/nginx/ssl/astra-local.ds.crt;
    ssl_certificate_key /etc/nginx/ssl/astra-local.ds.key;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
