export const enum RegionEnum {
	None = 'None',
	Albania = 'Албания',
	Andorra = 'Андорра',
	Austria = 'Австрия',
	Belarus = 'Беларусь',
	Belgium = 'Бельгия',
	BosniaAndHerzegovina = 'Босния и Герцеговина',
	Bulgaria = 'Болгария',
	Croatia = 'Хорватия',
	Cyprus = 'Кипр',
	CzechRepublic = 'Чехия',
	Denmark = 'Дания',
	Estonia = 'Эстония',
	Finland = 'Финляндия',
	France = 'Франция',
	Germany = 'Германия',
	Greece = 'Греция',
	Hungary = 'Венгрия',
	Iceland = 'Исландия',
	Ireland = 'Ирландия',
	Italy = 'Италия',
	Latvia = 'Латвия',
	Lithuania = 'Литва',
	Luxembourg = 'Люксембург',
	Malta = 'Мальта',
	Moldova = 'Молдова',
	Monaco = 'Монако',
	Montenegro = 'Черногория',
	Netherlands = 'Нидерланды',
	NorthMacedonia = 'Северная Македония',
	Norway = 'Норвегия',
	Poland = 'Польша',
	Portugal = 'Португалия',
	Romania = 'Румыния',
	Russia = 'Россия',
	SanMarino = 'Сан-Марино',
	Serbia = 'Сербия',
	Slovakia = 'Словакия',
	Slovenia = 'Словения',
	Spain = 'Испания',
	Sweden = 'Швеция',
	Switzerland = 'Швейцария',
	Ukraine = 'Украина',
}

export enum PriorityEnum {
	Low = 'Низкий',
	Medium = 'Средний',
	High = 'Высокий',
}

export enum MaterialOriginTypeEnum {
	Generic = 'Общий',
	Manufacturer = 'Производитель',
	UserDefinedProduct = 'Пользовательский продукт',
}
