export enum Country {
	None = 'None',
	Albania = 'Albania',
	Andorra = 'Andorra',
	Austria = 'Austria',
	Belarus = 'Belarus',
	Belgium = 'Belgium',
	BosniaAndHerzegovina = 'BosniaAndHerzegovina',
	Bulgaria = 'Bulgaria',
	Croatia = 'Croatia',
	Cyprus = 'Cyprus',
	CzechRepublic = 'CzechRepublic',
	Denmark = 'Denmark',
	Estonia = 'Estonia',
	Finland = 'Finland',
	France = 'France',
	Germany = 'Germany',
	Greece = 'Greece',
	Hungary = 'Hungary',
	Iceland = 'Iceland',
	Ireland = 'Ireland',
	Italy = 'Italy',
	Latvia = 'Latvia',
	Lithuania = 'Lithuania',
	Luxembourg = 'Luxembourg',
	Malta = 'Malta',
	Moldova = 'Moldova',
	Monaco = 'Monaco',
	Montenegro = 'Montenegro',
	Netherlands = 'Netherlands',
	NorthMacedonia = 'NorthMacedonia',
	Norway = 'Norway',
	Poland = 'Poland',
	Portugal = 'Portugal',
	Romania = 'Romania',
	Russia = 'Russia',
	SanMarino = 'SanMarino',
	Serbia = 'Serbia',
	Slovakia = 'Slovakia',
	Slovenia = 'Slovenia',
	Spain = 'Spain',
	Sweden = 'Sweden',
	Switzerland = 'Switzerland',
	Ukrain = 'Ukrain',
}

export const RuCountryNamesSelectValues = [
	{ label: 'Нет', value: Country.None },
	{ label: 'Албания', value: Country.Albania },
	{ label: 'Андорра', value: Country.Andorra },
	{ label: 'Австрия', value: Country.Austria },
	{ label: 'Беларусь', value: Country.Belarus },
	{ label: 'Бельгия', value: Country.Belgium },
	{ label: 'Босния и Герцеговина', value: Country.BosniaAndHerzegovina },
	{ label: 'Болгария', value: Country.Bulgaria },
	{ label: 'Хорватия', value: Country.Croatia },
	{ label: 'Кипр', value: Country.Cyprus },
	{ label: 'Чехия', value: Country.CzechRepublic },
	{ label: 'Дания', value: Country.Denmark },
	{ label: 'Эстония', value: Country.Estonia },
	{ label: 'Финляндия', value: Country.Finland },
	{ label: 'Франция', value: Country.France },
	{ label: 'Германия', value: Country.Germany },
	{ label: 'Греция', value: Country.Greece },
	{ label: 'Венгрия', value: Country.Hungary },
	{ label: 'Исландия', value: Country.Iceland },
	{ label: 'Ирландия', value: Country.Ireland },
	{ label: 'Италия', value: Country.Italy },
	{ label: 'Латвия', value: Country.Latvia },
	{ label: 'Литва', value: Country.Lithuania },
	{ label: 'Люксембург', value: Country.Luxembourg },
	{ label: 'Мальта', value: Country.Malta },
	{ label: 'Молдова', value: Country.Moldova },
	{ label: 'Монако', value: Country.Monaco },
	{ label: 'Черногория', value: Country.Montenegro },
	{ label: 'Нидерланды', value: Country.Netherlands },
	{ label: 'Северная Македония', value: Country.NorthMacedonia },
	{ label: 'Норвегия', value: Country.Norway },
	{ label: 'Польша', value: Country.Poland },
	{ label: 'Португалия', value: Country.Portugal },
	{ label: 'Румыния', value: Country.Romania },
	{ label: 'Россия', value: Country.Russia },
	{ label: 'Сан-Марино', value: Country.SanMarino },
	{ label: 'Сербия', value: Country.Serbia },
	{ label: 'Словакия', value: Country.Slovakia },
	{ label: 'Словения', value: Country.Slovenia },
	{ label: 'Испания', value: Country.Spain },
	{ label: 'Швеция', value: Country.Sweden },
	{ label: 'Швейцария', value: Country.Switzerland },
	{ label: 'Украина', value: Country.Ukrain }
];
