export enum Country {
	None = 'None',
	Albania = 'Albania',
	Andorra = 'Andorra',
	Austria = 'Austria',
	Belarus = 'Belarus',
	Belgium = 'Belgium',
	BosniaAndHerzegovina = 'BosniaAndHerzegovina',
	Bulgaria = 'Bulgaria',
	Croatia = 'Croatia',
	Cyprus = 'Cyprus',
	CzechRepublic = 'CzechRepublic',
	Denmark = 'Denmark',
	Estonia = 'Estonia',
	Finland = 'Finland',
	France = 'France',
	Germany = 'Germany',
	Greece = 'Greece',
	Hungary = 'Hungary',
	Iceland = 'Iceland',
	Ireland = 'Ireland',
	Italy = 'Italy',
	Latvia = 'Latvia',
	Lithuania = 'Lithuania',
	Luxembourg = 'Luxembourg',
	Malta = 'Malta',
	Moldova = 'Moldova',
	Monaco = 'Monaco',
	Montenegro = 'Montenegro',
	Netherlands = 'Netherlands',
	NorthMacedonia = 'NorthMacedonia',
	Norway = 'Norway',
	Poland = 'Poland',
	Portugal = 'Portugal',
	Romania = 'Romania',
	Russia = 'Russia',
	SanMarino = 'SanMarino',
	Serbia = 'Serbia',
	Slovakia = 'Slovakia',
	Slovenia = 'Slovenia',
	Spain = 'Spain',
	Sweden = 'Sweden',
	Switzerland = 'Switzerland',
	Ukrain = 'Ukrain',
}

export const RuCountryNamesMap = {
	None: 'Нет',
	Albania: 'Албания',
	Andorra: 'Андорра',
	Austria: 'Австрия',
	Belarus: 'Беларусь',
	Belgium: 'Бельгия',
	BosniaAndHerzegovina: 'Босния и Герцеговина',
	Bulgaria: 'Болгария',
	Croatia: 'Хорватия',
	Cyprus: 'Кипр',
	CzechRepublic: 'Чехия',
	Denmark: 'Дания',
	Estonia: 'Эстония',
	Finland: 'Финляндия',
	France: 'Франция',
	Germany: 'Германия',
	Greece: 'Греция',
	Hungary: 'Венгрия',
	Iceland: 'Исландия',
	Ireland: 'Ирландия',
	Italy: 'Италия',
	Latvia: 'Латвия',
	Lithuania: 'Литва',
	Luxembourg: 'Люксембург',
	Malta: 'Мальта',
	Moldova: 'Молдова',
	Monaco: 'Монако',
	Montenegro: 'Черногория',
	Netherlands: 'Нидерланды',
	NorthMacedonia: 'Северная Македония',
	Norway: 'Норвегия',
	Poland: 'Польша',
	Portugal: 'Португалия',
	Romania: 'Румыния',
	Russia: 'Россия',
	SanMarino: 'Сан-Марино',
	Serbia: 'Сербия',
	Slovakia: 'Словакия',
	Slovenia: 'Словения',
	Spain: 'Испания',
	Sweden: 'Швеция',
	Switzerland: 'Швейцария',
	Ukrain: 'Украина',
};

export const RuCountryNamesSelectValues = [
	{ label: 'Нет', value: Country.None },
	{ label: 'Албания', value: Country.Albania },
	{ label: 'Андорра', value: Country.Andorra },
	{ label: 'Австрия', value: Country.Austria },
	{ label: 'Беларусь', value: Country.Belarus },
	{ label: 'Бельгия', value: Country.Belgium },
	{ label: 'Босния и Герцеговина', value: Country.BosniaAndHerzegovina },
	{ label: 'Болгария', value: Country.Bulgaria },
	{ label: 'Хорватия', value: Country.Croatia },
	{ label: 'Кипр', value: Country.Cyprus },
	{ label: 'Чехия', value: Country.CzechRepublic },
	{ label: 'Дания', value: Country.Denmark },
	{ label: 'Эстония', value: Country.Estonia },
	{ label: 'Финляндия', value: Country.Finland },
	{ label: 'Франция', value: Country.France },
	{ label: 'Германия', value: Country.Germany },
	{ label: 'Греция', value: Country.Greece },
	{ label: 'Венгрия', value: Country.Hungary },
	{ label: 'Исландия', value: Country.Iceland },
	{ label: 'Ирландия', value: Country.Ireland },
	{ label: 'Италия', value: Country.Italy },
	{ label: 'Латвия', value: Country.Latvia },
	{ label: 'Литва', value: Country.Lithuania },
	{ label: 'Люксембург', value: Country.Luxembourg },
	{ label: 'Мальта', value: Country.Malta },
	{ label: 'Молдова', value: Country.Moldova },
	{ label: 'Монако', value: Country.Monaco },
	{ label: 'Черногория', value: Country.Montenegro },
	{ label: 'Нидерланды', value: Country.Netherlands },
	{ label: 'Северная Македония', value: Country.NorthMacedonia },
	{ label: 'Норвегия', value: Country.Norway },
	{ label: 'Польша', value: Country.Poland },
	{ label: 'Португалия', value: Country.Portugal },
	{ label: 'Румыния', value: Country.Romania },
	{ label: 'Россия', value: Country.Russia },
	{ label: 'Сан-Марино', value: Country.SanMarino },
	{ label: 'Сербия', value: Country.Serbia },
	{ label: 'Словакия', value: Country.Slovakia },
	{ label: 'Словения', value: Country.Slovenia },
	{ label: 'Испания', value: Country.Spain },
	{ label: 'Швеция', value: Country.Sweden },
	{ label: 'Швейцария', value: Country.Switzerland },
	{ label: 'Украина', value: Country.Ukrain },
];

export const country2title: Record<Country, string> = {
	[Country.None]: 'Нет',
	[Country.Albania]: 'Албания',
	[Country.Andorra]: 'Андорра',
	[Country.Austria]: 'Австрия',
	[Country.Belarus]: 'Беларусь',
	[Country.Belgium]: 'Бельгия',
	[Country.BosniaAndHerzegovina]: 'Босния и Герцеговина',
	[Country.Bulgaria]: 'Болгария',
	[Country.Croatia]: 'Хорватия',
	[Country.Cyprus]: 'Кипр',
	[Country.CzechRepublic]: 'Чехия',
	[Country.Denmark]: 'Дания',
	[Country.Estonia]: 'Эстония',
	[Country.Finland]: 'Финляндия',
	[Country.France]: 'Франция',
	[Country.Germany]: 'Германия',
	[Country.Greece]: 'Греция',
	[Country.Hungary]: 'Венгрия',
	[Country.Iceland]: 'Исландия',
	[Country.Ireland]: 'Ирландия',
	[Country.Italy]: 'Италия',
	[Country.Latvia]: 'Латвия',
	[Country.Lithuania]: 'Литва',
	[Country.Luxembourg]: 'Люксембург',
	[Country.Malta]: 'Мальта',
	[Country.Moldova]: 'Молдова',
	[Country.Monaco]: 'Монако',
	[Country.Montenegro]: 'Черногория',
	[Country.Netherlands]: 'Нидерланды',
	[Country.NorthMacedonia]: 'Северная Македония',
	[Country.Norway]: 'Норвегия',
	[Country.Poland]: 'Польша',
	[Country.Portugal]: 'Португалия',
	[Country.Romania]: 'Румыния',
	[Country.Russia]: 'Россия',
	[Country.SanMarino]: 'Сан-Марино',
	[Country.Serbia]: 'Сербия',
	[Country.Slovakia]: 'Словакия',
	[Country.Slovenia]: 'Словения',
	[Country.Spain]: 'Испания',
	[Country.Sweden]: 'Швеция',
	[Country.Switzerland]: 'Швейцария',
	[Country.Ukrain]: 'Украина',
};

export const EnCountryNamesSelectValues = [
	{ label: 'None', value: Country.None },
	{ label: 'Albania', value: Country.Albania },
	{ label: 'Andorra', value: Country.Andorra },
	{ label: 'Austria', value: Country.Austria },
	{ label: 'Belarus', value: Country.Belarus },
	{ label: 'Belgium', value: Country.Belgium },
	{ label: 'Bosnia and Herzegovina', value: Country.BosniaAndHerzegovina },
	{ label: 'Bulgaria', value: Country.Bulgaria },
	{ label: 'Croatia', value: Country.Croatia },
	{ label: 'Cyprus', value: Country.Cyprus },
	{ label: 'Czech Republic', value: Country.CzechRepublic },
	{ label: 'Denmark', value: Country.Denmark },
	{ label: 'Estonia', value: Country.Estonia },
	{ label: 'Finland', value: Country.Finland },
	{ label: 'France', value: Country.France },
	{ label: 'Germany', value: Country.Germany },
	{ label: 'Greece', value: Country.Greece },
	{ label: 'Hungary', value: Country.Hungary },
	{ label: 'Iceland', value: Country.Iceland },
	{ label: 'Ireland', value: Country.Ireland },
	{ label: 'Italy', value: Country.Italy },
	{ label: 'Latvia', value: Country.Latvia },
	{ label: 'Lithuania', value: Country.Lithuania },
	{ label: 'Luxembourg', value: Country.Luxembourg },
	{ label: 'Malta', value: Country.Malta },
	{ label: 'Moldova', value: Country.Moldova },
	{ label: 'Monaco', value: Country.Monaco },
	{ label: 'Montenegro', value: Country.Montenegro },
	{ label: 'Netherlands', value: Country.Netherlands },
	{ label: 'North Macedonia', value: Country.NorthMacedonia },
	{ label: 'Norway', value: Country.Norway },
	{ label: 'Poland', value: Country.Poland },
	{ label: 'Portugal', value: Country.Portugal },
	{ label: 'Romania', value: Country.Romania },
	{ label: 'Russia', value: Country.Russia },
	{ label: 'San Marino', value: Country.SanMarino },
	{ label: 'Serbia', value: Country.Serbia },
	{ label: 'Slovakia', value: Country.Slovakia },
	{ label: 'Slovenia', value: Country.Slovenia },
	{ label: 'Spain', value: Country.Spain },
	{ label: 'Sweden', value: Country.Sweden },
	{ label: 'Switzerland', value: Country.Switzerland },
	{ label: 'Ukraine', value: Country.Ukrain },
];
