export enum Region {
	None = 'None',
	Albania = 'Albania',
	Andorra = 'Andorra',
	Austria = 'Austria',
	Belarus = 'Belarus',
	Belgium = 'Belgium',
	BosniaAndHerzegovina = 'BosniaAndHerzegovina',
	Bulgaria = 'Bulgaria',
	Croatia = 'Croatia',
	Cyprus = 'Cyprus',
	CzechRepublic = 'CzechRepublic',
	Denmark = 'Denmark',
	Estonia = 'Estonia',
	Finland = 'Finland',
	France = 'France',
	Germany = 'Germany',
	Greece = 'Greece',
	Hungary = 'Hungary',
	Iceland = 'Iceland',
	Ireland = 'Ireland',
	Italy = 'Italy',
	Latvia = 'Latvia',
	Lithuania = 'Lithuania',
	Luxembourg = 'Luxembourg',
	Malta = 'Malta',
	Moldova = 'Moldova',
	Monaco = 'Monaco',
	Montenegro = 'Montenegro',
	Netherlands = 'Netherlands',
	NorthMacedonia = 'NorthMacedonia',
	Norway = 'Norway',
	Poland = 'Poland',
	Portugal = 'Portugal',
	Romania = 'Romania',
	Russia = 'Russia',
	SanMarino = 'SanMarino',
	Serbia = 'Serbia',
	Slovakia = 'Slovakia',
	Slovenia = 'Slovenia',
	Spain = 'Spain',
	Sweden = 'Sweden',
	Switzerland = 'Switzerland',
	Ukrain = 'Ukrain',
}

export const RuRegionNamesMap = {
	None: 'Нет',
	Albania: 'Албания',
	Andorra: 'Андорра',
	Austria: 'Австрия',
	Belarus: 'Беларусь',
	Belgium: 'Бельгия',
	BosniaAndHerzegovina: 'Босния и Герцеговина',
	Bulgaria: 'Болгария',
	Croatia: 'Хорватия',
	Cyprus: 'Кипр',
	CzechRepublic: 'Чехия',
	Denmark: 'Дания',
	Estonia: 'Эстония',
	Finland: 'Финляндия',
	France: 'Франция',
	Germany: 'Германия',
	Greece: 'Греция',
	Hungary: 'Венгрия',
	Iceland: 'Исландия',
	Ireland: 'Ирландия',
	Italy: 'Италия',
	Latvia: 'Латвия',
	Lithuania: 'Литва',
	Luxembourg: 'Люксембург',
	Malta: 'Мальта',
	Moldova: 'Молдова',
	Monaco: 'Монако',
	Montenegro: 'Черногория',
	Netherlands: 'Нидерланды',
	NorthMacedonia: 'Северная Македония',
	Norway: 'Норвегия',
	Poland: 'Польша',
	Portugal: 'Португалия',
	Romania: 'Румыния',
	Russia: 'Россия',
	SanMarino: 'Сан-Марино',
	Serbia: 'Сербия',
	Slovakia: 'Словакия',
	Slovenia: 'Словения',
	Spain: 'Испания',
	Sweden: 'Швеция',
	Switzerland: 'Швейцария',
	Ukrain: 'Украина',
};

export const RuRegionNamesSelectValues = [
	{ label: 'Нет', value: Region.None },
	{ label: 'Албания', value: Region.Albania },
	{ label: 'Андорра', value: Region.Andorra },
	{ label: 'Австрия', value: Region.Austria },
	{ label: 'Беларусь', value: Region.Belarus },
	{ label: 'Бельгия', value: Region.Belgium },
	{ label: 'Босния и Герцеговина', value: Region.BosniaAndHerzegovina },
	{ label: 'Болгария', value: Region.Bulgaria },
	{ label: 'Хорватия', value: Region.Croatia },
	{ label: 'Кипр', value: Region.Cyprus },
	{ label: 'Чехия', value: Region.CzechRepublic },
	{ label: 'Дания', value: Region.Denmark },
	{ label: 'Эстония', value: Region.Estonia },
	{ label: 'Финляндия', value: Region.Finland },
	{ label: 'Франция', value: Region.France },
	{ label: 'Германия', value: Region.Germany },
	{ label: 'Греция', value: Region.Greece },
	{ label: 'Венгрия', value: Region.Hungary },
	{ label: 'Исландия', value: Region.Iceland },
	{ label: 'Ирландия', value: Region.Ireland },
	{ label: 'Италия', value: Region.Italy },
	{ label: 'Латвия', value: Region.Latvia },
	{ label: 'Литва', value: Region.Lithuania },
	{ label: 'Люксембург', value: Region.Luxembourg },
	{ label: 'Мальта', value: Region.Malta },
	{ label: 'Молдова', value: Region.Moldova },
	{ label: 'Монако', value: Region.Monaco },
	{ label: 'Черногория', value: Region.Montenegro },
	{ label: 'Нидерланды', value: Region.Netherlands },
	{ label: 'Северная Македония', value: Region.NorthMacedonia },
	{ label: 'Норвегия', value: Region.Norway },
	{ label: 'Польша', value: Region.Poland },
	{ label: 'Португалия', value: Region.Portugal },
	{ label: 'Румыния', value: Region.Romania },
	{ label: 'Россия', value: Region.Russia },
	{ label: 'Сан-Марино', value: Region.SanMarino },
	{ label: 'Сербия', value: Region.Serbia },
	{ label: 'Словакия', value: Region.Slovakia },
	{ label: 'Словения', value: Region.Slovenia },
	{ label: 'Испания', value: Region.Spain },
	{ label: 'Швеция', value: Region.Sweden },
	{ label: 'Швейцария', value: Region.Switzerland },
	{ label: 'Украина', value: Region.Ukrain },
];
